/*
 * File: app/view/MyFieldSet.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyFieldSet', {
    extend: 'Ext.form.FieldSet',

    config: {
        height: 461,
        width: 299,
        title: 'Grade',
        items: [
            {
                xtype: 'textfield',
                id: 'Win',
                label: 'Win'
            },
            {
                xtype: 'textfield',
                id: 'Loss',
                label: 'Loss'
            },
            {
                xtype: 'textfield',
                id: 'Record',
                label: 'Record'
            },
            {
                xtype: 'image',
                height: 210,
                src: 'http://smallprogramdesign.com/myapp//horseracing.jpg'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    var win =  Ext.getCmp('Win').getValue();  // win id
                    var loss =  Ext.getCmp('Loss').getValue();  // loss id
                    var record =  Ext.getCmp('Record').getValue();  // record id 
                    alert( "Horse Grade is " + ((record/(win - (loss * 1/5)))*100).toFixed(2));

                },
                ui: 'confirm',
                text: 'Calculate'
            }
        ]
    }

});