/*
 * File: app/view/MyFieldSet.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyFieldSet', {
    extend: 'Ext.form.FieldSet',

    config: {
        height: 329,
        ui: '',
        width: 302,
        scrollable: false,
        items: [
            {
                xtype: 'textfield',
                id: 'Win',
                label: 'Win',
                placeHolder: 'ex. 202.89'
            },
            {
                xtype: 'textfield',
                id: 'Loss',
                label: 'Loss',
                placeHolder: 'ex. 9.5'
            },
            {
                xtype: 'textfield',
                id: 'Record',
                label: 'Record',
                placeHolder: 'ex. 201.4'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    var win =  parseFloat(Ext.getCmp('Win').getValue());  // win id
                    var loss = parseFloat((Ext.getCmp('Loss').getValue()*1/5));  // loss id
                    var record =  parseFloat(Ext.getCmp('Record').getValue());  // record id 
                    var grade = (record/(win+loss)*100).toFixed(2);


                    alert(	"Win is " + win + "\n" +
                    "Loss is " + loss + "\n" +
                    "Record is " + record + "\n\n" + 
                    "Horse Grade is " + grade);

                },
                height: 33,
                ui: 'confirm',
                text: 'Calculate'
            },
            {
                xtype: 'image',
                height: 166,
                width: 299,
                src: 'http://smallprogramdesign.com/myapp/horseracing.jpg'
            }
        ]
    }

});